// <auto-generated />
using System;
using InventoryManagamentSystem_WPF_DB.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagamentSystem_WPF_DB.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20250522194613_TPTImplementation")]
    partial class TPTImplementation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagamentSystem_WPF_DB.DTOs.ProductDTO", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("InventoryManagamentSystem_WPF_DB.DTOs.ClothingProductDTO", b =>
                {
                    b.HasBaseType("InventoryManagamentSystem_WPF_DB.DTOs.ProductDTO");

                    b.Property<string>("Fabric")
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Size")
                        .HasColumnType("varchar(5)");

                    b.ToTable("ClothingProducts", (string)null);
                });

            modelBuilder.Entity("InventoryManagamentSystem_WPF_DB.DTOs.ElectronicsProductDTO", b =>
                {
                    b.HasBaseType("InventoryManagamentSystem_WPF_DB.DTOs.ProductDTO");

                    b.Property<int>("BatteryCapacity")
                        .HasColumnType("int");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(7, 2)");

                    b.ToTable("ElectronicProducts", (string)null);
                });

            modelBuilder.Entity("InventoryManagamentSystem_WPF_DB.DTOs.PerishableGoodsProductDTO", b =>
                {
                    b.HasBaseType("InventoryManagamentSystem_WPF_DB.DTOs.ProductDTO");

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.ToTable("PerishableGoodsProducts", (string)null);
                });

            modelBuilder.Entity("InventoryManagamentSystem_WPF_DB.DTOs.ClothingProductDTO", b =>
                {
                    b.HasOne("InventoryManagamentSystem_WPF_DB.DTOs.ProductDTO", null)
                        .WithOne()
                        .HasForeignKey("InventoryManagamentSystem_WPF_DB.DTOs.ClothingProductDTO", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagamentSystem_WPF_DB.DTOs.ElectronicsProductDTO", b =>
                {
                    b.HasOne("InventoryManagamentSystem_WPF_DB.DTOs.ProductDTO", null)
                        .WithOne()
                        .HasForeignKey("InventoryManagamentSystem_WPF_DB.DTOs.ElectronicsProductDTO", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InventoryManagamentSystem_WPF_DB.DTOs.PerishableGoodsProductDTO", b =>
                {
                    b.HasOne("InventoryManagamentSystem_WPF_DB.DTOs.ProductDTO", null)
                        .WithOne()
                        .HasForeignKey("InventoryManagamentSystem_WPF_DB.DTOs.PerishableGoodsProductDTO", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
