using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace InventoryManagamentSystem_WPF_DB.Models
{
    public class ElectronicsProduct: Product
    {
        public decimal Voltage { get; }
        public int BatteryCapacity { get; }
        // Used for filling in data into it from viewModel (ID is not needed as later it will be filled in from db)
        public ElectronicsProduct(string name, ProductCategoryEnum productCategory, decimal price, int quantity, decimal voltage, int batteryCapacity): base(name, productCategory, price, quantity)
        {
            Voltage = voltage;
            BatteryCapacity = batteryCapacity;
        }
        // Used for filling in data to product model trough DB (ID is autogenerated)
        public ElectronicsProduct(int id, string name, ProductCategoryEnum productCategory, decimal price, int quantity, decimal voltage, int batteryCapacity) : base(id, name, productCategory, price, quantity)
        {
            Voltage = voltage;
            BatteryCapacity = batteryCapacity;
        }
        public override string ToString()
        {
            return base.ToString() + $"\nVoltage: {Voltage}\nBattery Capacity: {BatteryCapacity}";
        }
    }
}
